from . import procurement_group
from . import res_company
from . import res_config_settings
from . import stock_location
from . import stock_location_route
from . import stock_move
from . import stock_move_line
from . import stock_picking
from . import stock_request
from . import stock_request_abstract
from . import stock_request_allocation
from . import stock_request_order
from . import stock_rule
from . import stock_warehouse
